TenKeyLabs/dappwright

- src/bootstrap.ts
- src/launch.ts
- src/wallets/metamask/setup/downloader.ts
- test/test.spec.ts
many files were still showing up in the current directory after running. This was causing some messy commits in projects that consume this lib.
> makes consistent use of tmp dirs for generated/downloaded files

- .changeset/few-melons-impress.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- src/wallets/metamask/metamask.ts
- src/wallets/metamask/setup/downloader.ts
- src/wallets/wallet.ts
- src/wallets/wallets.ts
This implements a new way of dynamically extracting the chrome extension id of the chrome extensions in order to navigate to their respective home pages.
- dappwright will navigate to the `chrome://system` page to extract a dynamically generated chrome id
Closes #50
> fix: Implements a dynamic way of reaching the homepage of a chrome extension

- .changeset/healthy-poets-act.md
- .changeset/soft-keys-notice.md
- src/wallets/coinbase/actions.ts
This fixes an issue where the switchAccount & deleteNetwork actions for Coinbase Wallet weren't waiting for the click to complete causing a race condition in certain scenarios.
> fix: adds missing await for coinbase accountSwitch & deleteNetwork clicks

- .changeset/honest-glasses-wonder.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
Navigating to the homepage after the initial setup allows for follow up actions to have a good starting state when invoked in an overall test environment setup.
```typescript
const [coinbase, page, context] = await dappwright.bootstrap("", {
wallet: "coinbase",
version: CoinbaseWallet.recommendedVersion,
seed: process.env.DAPPWRIGHT_SEED,
});
await coinbase.createAccount();
```
> fix: navigate home after coinbase setup

- .changeset/proud-teachers-collect.md
- src/types.ts
This exports the wallet types primarily so they can be used when initializing the wallets with the recommended version.
> feat: exports wallet types

- .changeset/polite-dolls-rescue.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- test/2-wallet.spec.ts
- tsconfig.json
Adds support for Coinbase Wallet 3.6.0. Also fixes static token symbol reference for Coinbase Wallet when using getTokenBalance
> chore: support for Coinbase Wallet 3.6.0

- .changeset/silver-olives-smell.md
- src/wallets/metamask/setup/downloader.ts
- src/wallets/wallets.ts
This ensures that chrome extensions are loaded with consistent IDs. Normally they are different based on the system. This greatly reduces the complexity in finding the wallets that we're loading into the browser.
Should help towards #53 since headless mode was getting `page.goto: net::ERR_INVALID_URL at chrome://system` errors.
> chore: extensions load with consistent ids

- .changeset/hungry-weeks-sell.md
- src/wallets/metamask/setup/downloader.ts
There was an issue where the extensions were downloading when they were already on every run downloaded, but not unzipped. This gets the package paths to be aligned.
> fix: cache path mismatch in the downloader

- .changeset/clean-experts-count.md
- src/wallets/coinbase/coinbase.ts
The repo for Coinbase Wallet releases has moved to the Ten Key Labs org and this updates the url.
> chore: updates the releases repo for coinbase wallet

- .changeset/wicked-squids-sin.md
- package.json
- src/helpers/actions.ts
- src/index.ts
- src/wallets/coinbase/actions.ts
- src/wallets/metamask/actions/addNetwork.ts
- src/wallets/metamask/actions/confirmTransaction.ts
- src/wallets/metamask/actions/helpers/actions.ts
- test/2-wallet.spec.ts
This cleans up a few lingering warnings that have been around since the initial fork.
```
Circular dependency: src/wallets/metamask/actions/helpers/index.ts -> src/wallets/metamask/actions/helpers/actions.ts -> src/wallets/metamask/actions/helpers/index.ts
Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `dappwright["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
Circular dependency: src/wallets/metamask/actions/helpers/index.ts -> src/wallets/metamask/actions/helpers/actions.ts -> src/wallets/metamask/actions/helpers/index.ts
Circular dependency: src/wallets/metamask/actions/helpers/index.ts -> src/wallets/metamask/actions/helpers/actions.ts -> …
```
> chore: cleans up imports/exports

- .github/workflows/test.yaml
- package.json
Moves the tests to use the [official playwright docker images](https://mcr.microsoft.com/en-us/product/playwright/about).
Special thanks to @FranciszekMalcher for letting us know about these in #101. This initial implementation will use playwright 1.30 for compatibility purposes and will help with the next few bumps.
> chore: updates tests to use the official docker image

- .changeset/twenty-fireants-invite.md
- .github/workflows/test.yaml
- package.json
- yarn.lock
bumps playwright dependencies to the latest versions.
> chore: bumps playwright and playwright/core to 1.32.3

- .changeset/rude-lobsters-wonder.md
- package.json
Node 16 is still supported but will be EOL September 2023. Folks are moving to 18 and this will allow a graceful transition.
Closes #105
> chore: enables support for engines > 16

- .changeset/good-ducks-tan.md
- src/bootstrap.ts
- src/launch.ts
- src/types.ts
**Add support for parallel testing.**
This pull request adds support for parallel testing by creating a separate Playwright user data directory for each worker. This prevents the workers from interfering with each other and allows them to run independently.
It reads the worker index from `process.env.TEST_WORKER_INDEX` like stated [here](https://playwright.dev/docs/test-parallel#worker-index-and-parallel-index).
> feat: run tests in parallel

- .changeset/tidy-pets-argue.md
- src/wallets/metamask/actions/switchNetwork.ts
- test/2-wallet.spec.ts
Fixes #240 
This will require exact text matches for switching networks.
> fix: exact text matches for switching networks

- .changeset/witty-bees-cheat.md
- src/wallets/metamask/actions/switchAccount.ts
Fixes #233
Tighter scope on the selector so that playwright doesn't get confused by the other account button on the main page.
> fix: scope of switch account selector to the menu dialog

- .changeset/dry-lizards-battle.md
- src/wallets/metamask/setup/setupActions.ts
- test/helpers/walletTest.ts
Fixes #246. Adjusts tests to protect from this bad scenario in the future.
> fix: metamask not settling on the homescreen after settings adjustments

- .changeset/unlucky-bottles-melt.md
- src/types.ts
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- src/wallets/metamask/actions/approve.ts
- src/wallets/metamask/actions/index.ts
- src/wallets/metamask/actions/signin.ts
- src/wallets/metamask/metamask.ts
- src/wallets/wallet.ts
- test/3-dapp.spec.ts
- test/dapp/public/index.html
- test/dapp/public/main.js
- Abstracts connect action to be used for a connect or signin since the former is a subset of the latter.
- Implements Sign In action for Metamask
- Adds tests for both the initial signin flow, and a re-signin
Closes #271
> feat: adds support for signin operations

- .changeset/spotty-ravens-joke.md
- src/wallets/metamask/actions/approve.ts
- src/wallets/metamask/metamask.ts
- src/wallets/metamask/setup/setupActions.ts
- test/2-wallet.spec.ts
- test/3-dapp.spec.ts
- Bumps Metamask to 11.16.3
- Adjusts for UX changes
- Switches tests from Goerli to Sepolia
Closes #337
Curious if this helps with #321
> chore: bump metamask

- .changeset/lazy-singers-hope.md
- src/wallets/metamask/metamask.ts
bumps MetaMask to 11.16.3 as a possible fix for #344
> chore: bumps metamask to 11.16.13

- src/wallets/metamask/actions/signin.ts
- test/3-dapp.spec.ts
- test/dapp/public/index.html
- test/dapp/public/main.js
This PR fixes the signIn action for MetaMask to support SIWE-compliant messages.
MetaMask displays a different UI with alternate text when handling SIWE-compliant messages, which caused issues in the current implementation. The original code relied on detecting the “Signature request” header and interacting with a button labeled “Sign.” However, this approach failed when the UI varied for SIWE requests.
The core change is in the signIn method, where a check for “Sign-in request” was added. Instead of relying on the button text to identify the clickable element, the update now uses the testId directive. This directive is common to both button types, handling SIWE-compliant messages as well as regular signature requests.
- `signIn` method
- Include check …
> fix: siwe complient signature

- .changeset/thin-plants-sparkle.md
- package.json
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- test/2-wallet.spec.ts
- test/3-dapp.spec.ts
bumps coinbase to 3.96.0
- bumps coinbase to 3.96.0
- fetching the balance of an invalid token throws an error
Closes #396
> chore: bumps coinbase to 3.96.0

- .changeset/loud-bushes-return.md
- src/wallets/coinbase/coinbase.ts
> chore(coinbase): bump to 3.109.0

- package.json
- test/dapp/server.ts
- yarn.lock
bumps web3 from 1.10.0 to 4.16.0
> chore: bumps web3 from 1.10.0 to 4.16.0

- .changeset/smooth-baths-ring.md
- src/wallets/metamask/actions/helpers/actions.ts
Being more explicit about the account menu button being in view before clicking to see if it helps with #426.
#426
> fix(metamask): scroll account menu button into view before clicking

- .changeset/six-wasps-work.md
- src/wallets/metamask/actions/helpers/selectors.ts
- src/wallets/metamask/actions/importPk.ts
- src/wallets/metamask/metamask.ts
Bumps Metamask to 12.16.0.
Hopes this helps with #426
> chore: bumps metamask to 12.16.0

- .changeset/tricky-sloths-move.md
- src/downloader/downloader.ts
- src/downloader/github.ts
- src/downloader/version.ts
When running multiple projects at the same time, the logging for the downloader can be too generic which makes it hard to debug failure scenarios.
> chore: clearer worker downloader logging

- .changeset/nine-mirrors-rest.md
- src/bootstrap.ts
- src/wallets/wallets.ts
Slower CI cycles means that dappwright could possibly timeout on waiting for a new metamask setup screen, move on, then the screen popups up as an option for acquisition later on in the cycle.
Which would explain why in #426 it fails on the first action after bootstrap.
Closes #426
> fix(metamask): race condition leads to acquiring dormant page context

- .changeset/plenty-bugs-learn.md
- .github/workflows/release.yml
- .github/workflows/test.yaml
- package.json
Bumps the supported node version to >= 20.
> chore: bumps supported node version to >= 20

- .changeset/lemon-buttons-invite.md
- src/wallets/metamask/actions/addToken.ts
- src/wallets/metamask/actions/helpers/actions.ts
- src/wallets/metamask/setup/setupActions.ts
This replaces the "clickOnLogo" helper function for MetaMask with code to click the close button on screens that don't automatically return to the home screen after an action.
Closes #466
> chore: opt to click close buttons instead of the metamask logo to return home

- .changeset/friendly-countries-listen.md
- src/downloader/downloader.ts
- src/downloader/github.ts
There are more variants of chrome extensions coming out these days. Tightening up the matching logic for download extensions will ensure things remain deterministic.
Might be slightly related to the resolution to #473
> chore: adjusts the matching for downloaded versions more explicit

- .changeset/rude-parents-wonder.md
- src/wallets/coinbase/coinbase.ts
Bumps Coinbase Wallet to v3.123.0
> chore: bumps coinbase to v3.123.0

- package.json
- yarn.lock
bumps vitest from 2.1.8 to 3.2.4
> chore: bumps vitest from 2.1.8 to 3.2.4
