TenKeyLabs/dappwright

- src/setup/setupMetamask.ts
Fixes #2 by waiting for the dom to load before reloading the page.
> Wait for dom to load before refreshing Metamask opening page.

- package.json
- src/index.ts
- src/jest/config.ts
- src/types.ts
- test/jest/global.ts
This fixes the output and paths to typescript typings for better lookups and quicker local development.
> Fixes build output structure and type paths

- .github/dependabot.yml
This add a Dependabot config for dependency bump checks on a weekly basis.
> adds a dependabot config for weekly checks

- .changeset/early-otters-hunt.md
- src/wallets/metamask/actions/addNetwork.ts
- src/wallets/metamask/actions/confirmTransaction.ts
- src/wallets/metamask/actions/unlock.ts
- src/wallets/metamask/metamask.ts
- src/wallets/metamask/setup/setupActions.ts
- test/3-dapp.spec.ts
> chore: support for MetaMask 10.25.0

- src/wallets/coinbase/actions.ts
- _EXAMPLE - Removed basic auth from the controller_
Closes #
> fix: Update input name in coinbase wallet onboarding flow

- .changeset/nice-grapes-destroy.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- src/wallets/metamask/actions/countAccounts.ts
- src/wallets/metamask/metamask.ts
- src/wallets/wallet.ts
Adds a count accounts as a new feature and implements it for Coinbase Wallet.
> feat: Adds countAccounts to the wallet interface

- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- test/2-wallet.spec.ts
Bumps default supported version for Coinbase Wallet to 3.29.0
> chore: bumps coinbase wallet to 3.29.0

- src/wallets/metamask/metamask.ts
> fix: fixes a loose reference to MetaMask countAccount method

- .changeset/green-crabs-visit.md
- src/helpers/actions.ts
- src/wallets/metamask/actions/addNetwork.ts
- src/wallets/metamask/actions/addToken.ts
- src/wallets/metamask/actions/createAccount.ts
- src/wallets/metamask/actions/deleteAccount.ts
- src/wallets/metamask/actions/deleteNetwork.ts
- src/wallets/metamask/actions/getTokenBalance.ts
- src/wallets/metamask/actions/hasNetwork.ts
- src/wallets/metamask/actions/helpers/actions.ts
- src/wallets/metamask/actions/helpers/selectors.ts
- src/wallets/metamask/actions/importPk.ts
- src/wallets/metamask/actions/lock.ts
- src/wallets/metamask/actions/switchAccount.ts
- src/wallets/metamask/actions/switchNetwork.ts
- src/wallets/metamask/metamask.ts
- src/wallets/metamask/setup/setupActions.ts
- test/2-wallet.spec.ts
- test/helpers/walletTest.ts
Support for the major bump in MetaMask 11.
> feat: support for MetaMask 11.3

- .changeset/large-papayas-complain.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
> chore: bumps coinbase wallet to 3.42.0

- .changeset/weak-bears-repair.md
- src/wallets/coinbase/actions.ts
Updates to the newer `testid` Coinbase uses in the menu.
> fix: Coinbase network settings menu selector

- .changeset/strong-pumas-raise.md
- src/types.ts
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
- src/wallets/metamask/actions/index.ts
- src/wallets/metamask/actions/reject.ts
- src/wallets/metamask/metamask.ts
- test/3-dapp.spec.ts
- test/dapp/public/main.js
adds a reject action as discussed in https://github.com/TenKeyLabs/dappwright/discussions/215
Closes #215
> feat: adds reject action for metamask and coinbase wallet

- .changeset/wet-lobsters-press.md
- src/wallets/wallet.ts
> includes reject to fix wallet interface

- .changeset/got-it-button.md
- src/wallets/metamask/actions/addNetwork.ts
parallel checking of two elements on a page instead of sequential
Parallel promises to check elements on page
Resolves #290 
Closes #290
> fix: metamask add network got it popup

- .changeset/extensions-parametr.md
- .changeset/ninety-berries-destroy.md
- src/launch.ts
- src/types.ts
Add new parameter `additionalExtensions` for `dappwright.bootstrap`
Reslove #292 
Closes #292
> feat: 🎸 add new param for another extensions

- .changeset/metamask-update.md
- src/wallets/metamask/actions/addNetwork.ts
- src/wallets/metamask/metamask.ts
- test/2-wallet.spec.ts
Change few locators.
#302 
#302
> feat: 🎸 update metamask version to 2.7.5

- .changeset/sour-sheep-taste.md
- src/wallets/coinbase/actions.ts
- src/wallets/coinbase/coinbase.ts
Bumps Coinbase Wallet to 3.54.0
> chore: bumps coinbase wallet to 3.54.0

- .changeset/twenty-dingos-warn.md
- src/helpers/actions.ts
- src/wallets/metamask/actions/confirmTransaction.ts
- src/wallets/metamask/actions/deleteNetwork.ts
- src/wallets/metamask/actions/hasNetwork.ts
- src/wallets/metamask/actions/importPk.ts
- src/wallets/metamask/actions/switchNetwork.ts
- src/wallets/metamask/metamask.ts
- test/2-wallet.spec.ts
> chore: bumps metamask to 11.10.0

- .changeset/big-pumas-promise.md
- .changeset/spotty-ravens-joke.md
- src/wallets/coinbase/coinbase.ts
- src/wallets/metamask/actions/approve.ts
- src/wallets/metamask/metamask.ts
- src/wallets/metamask/setup/setupActions.ts
- test/2-wallet.spec.ts
- test/3-dapp.spec.ts
Bumps coinbase wallet to 3.70.0
> chore: bumps coinbase wallet to 3.70.0

- .changeset/shiny-mangos-deny.md
- src/launch.ts
**solve locale problem，always use English as brower‘s default language**
-  add brower args lang=en_us
Closes #
> fix: bug #329

- .github/workflows/test.yaml
- package.json
- yarn.lock
> chore: bumps playwright to 1.51.1

- .changeset/silver-foxes-show.md
- src/wallets/metamask/actions/addNetwork.ts
- src/wallets/metamask/actions/addToken.ts
- src/wallets/metamask/actions/approve.ts
- src/wallets/metamask/actions/getTokenBalance.ts
- src/wallets/metamask/actions/helpers/selectors.ts
- src/wallets/metamask/metamask.ts
- test/2-wallet.spec.ts
> chore: bumps metamask to 12.14.2
